services:
  - type: web
    name: text2img-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port=$PORT
    envVars:
      - key: HF_TOKEN
        sync: false
