services:
  - type: web
    name: text2img-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: HF_TOKEN
        sync: false
